version: '3'
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: always

  nginx:
    image: nginxdemos/hello:plain-text
    container_name: nginx
    hostname: nginx
    ports:
      - "8080:80"
    restart: always

